/**语言包  cn: 中文包；en：英文包；ja：日文包*/
var cn = {
    //index.html
    navigation_item1: '简介',
    navigation_item2: '背景及问题',
    navigation_item3: '解决方案',
    navigation_item4: '竞争优势',
    navigation_item5: '团队介绍',
    navigation_item6: '社区生态',
    registration_item: '加入白名单',

    sequence_item1: '基于区块链的全球去中心化游戏民有民治民享公共社区',
    sequence_item2: '白皮书',
    sequence_item2_first: '白皮书',
    sequence_item2_second: 'ENGLISH',
    sequence_item2_third: '日語',
    sequence_item2_fourth: '加入聊天群',

    //#industry_status
    industry_status_feature: '特点',
    industry_status_item1: '真正还政于民。建立由玩家民主评比作品和评论两大社区内容品质高下的良性竞争激励机制，透明公正，不能被任何人<span>操控</span>。',
    industry_status_item2: '抓<span>原创源头</span>。成熟的游戏众筹模式、为中文和日文独立开发者量身打造的引擎游戏制作工具BCreator.io、以及孵化场地等，支持帮助开发者梦想起航。GAME.FUND社区签约原创作品和优秀团队，储备内容资源战略高地。',
    industry_status_item3: '免下载安装<span>即点即玩</span>的新形态入口。<span>转化现有</span>重度原生为即点即玩模式，极大降低推广导量成本，顺应<span>移动互联网宽带</span>时代的HTML5 2.0，无限流量、千兆4G、5G时代重大利好接踵而来，必将成为业界新标准。',
    industry_status_item4: '信誉<span>数据宝库</span>。开发者、评论家的历史行为均被智能合约<span>烙印</span>在区块链中，可追溯不可篡改，形成各类决策所关键依托的大数据。',
    industry_status_item5: '基于区块链的平台SDK，实现去中心化游戏账号及数字财产的<span>确权</span>、及跨游戏<span>交易</span>贯通。',

    industry_status_feature1: '虚拟分布式的结构',
    industry_status_feature2: '高效率低成本的运作模式',
    industry_status_feature3: '去中心化的结构',
    industry_status_feature4: '多节点共识机制',
    industry_status_feature5: '分布式记账',

    //#service
    service_title1: '行业',
    service_title2: '背景及问题',
    service_title_item1: '抢占战略高地的窗口期',
    service_text_item1: '中文游戏早不再是增量市场，而是存量时代，品质和可玩性才是关键，游戏正在<span>回归初心</span>，中文玩家<span>正版付费</span>意识全面<span>振兴</span>，中文游戏文艺复兴黄金时代的朝阳正在冉冉升起。当下能以低成本来吸引开发者及其粉丝，是抢夺战略高地的历史难遇的<span>窗口时期</span>。',
    service_title_item2: '游戏众筹模式成熟',
    service_text_item2: '截至2017年9月，全球发起的游戏众筹项目数4万余个，共募集资金9亿美元，参投用户量1500万。反观中文游戏行业却“<span>势能矛盾</span>”突出：一方面愿为优秀游戏作品<span>付费的用户</span>群体已非常庞大，可另一方面有潜力的团队却极<span>难融资</span>，这种势能矛盾急需被一种模式击破“<span>泄洪</span>”。',
    service_title_item3: '区块链+游戏崭露头角',
    service_text_item3: '区块链领域一直缺少能实际落地项目，<span>假大空</span>横行。优秀新技术又一次从游戏领域率先落地实用，更多玩家关注区块链，而币圈投资人更接受游戏类项目。全球通过区块链数字货币方式的融资额已是<span>传统VC的两倍</span>，更是我们众筹模式的<span>N<sub>2</sub>O暴强加速剂</span>。',
    
    //#portfolio
    portfolio_title1: '解决方案',
    portfolio_title2: '与实现',
    portfolio_title_item1: '整体方案',
    portfolio_title_item2: '制作游戏',
    portfolio_title_item3: '玩游戏',
    portfolio_title_item4: '交流游戏',
    portfolio_title_item5: '区块链应用',

    Grid_title_item1: '游戏众筹社区',
    Grid_text_item1: '通过众筹对优秀创意项目进行投资，获得作品及相关资产的预购权乃至升值等回报，项目众筹达到或超过目标额度才算成功，否则全额退还给各资助者。',
    Grid_title_item2: '量身打造的创作利器',
    Grid_text_item2: '提供<span>华语</span>唯一<span>国际</span>水平高品质<span>游戏引擎</span>制作工具BCreator.io（也将发布英文版和日文版），内含图形NLP化<span>免编程</span>制作交互逻辑的模块Director极大降低了技术门槛，以便开发者选用创作游戏。',
    Grid_title_item3: '高品质游戏分发平台',
    Grid_text_item3: '社区吸纳优秀作品和开发者，聚集人气，并通过活动、直播、广告等方式吸引玩家。聚集大量玩家后，又能进一步吸引更多作品和优秀开发者入驻，形成<span>良性循环</span>。',
    Grid_title_item4: '即点即玩HTML5 2.0',
    Grid_text_item4: '实现了大型高品质<span>重度原生</span>游戏的“<span>免下载免安装即点即玩</span>”HTML5化。迎接无限流量、千兆4G、5G<span>移动宽带</span>互联网新时代，建立划时代的新形态的游戏入口模式。',
    Grid_title_item5: '高水准评论',
    Grid_text_item5: '实施<span>竞争</span>和<span>激励</span>机制，以及促进内容筛择评论者群体',
    Grid_title_item6: '直面粉丝意见',
    Grid_text_item6: '玩家与开发者<span>直接交流</span>，打磨作品。',
    Grid_title_item7: 'IM系统',
    Grid_text_item7: 'IM系统，为用户提供<span>即时通讯</span>服务',
    Grid_title_item8: '直播系统',
    Grid_text_item8: '有效提高社区<span>活跃度</span>提高游戏产品<span>收益</span>',
    Grid_title_item9: '互动社区',
    Grid_text_item9: '基于区块链的<span>公正透明</span>的激励机制。玩家、开发者、投资者、评论家、推广者在社区内外互动，互动行为皆由<span>智能合约</span>执行，并<span>烙印</span>至区块链。每一位社区成员都会有主人翁心态来主动推广和建设自己的社区。',
    Grid_title_item10: '区块链存取SDK',
    Grid_text_item10: '基于区块链的SDK，实现去中心化游戏账号及数字财产的<span>确权</span>，以及跨游戏<span>交易贯通</span>。并实现跨游戏的一键登入、平台通证结算手段、以及数字财产确权存取和交易贯通。',
    Grid_title_item11: '良性竞争激励机制',
    Grid_text_item11: '由区块链支撑两大良性竞争激励机制。作品和作品评论UGC的优秀与否，完全由<span>玩家决定</span>，确保社区高品质。区块链保障创始团队在内的任何人和势力均<span>不能控制和篡改</span>这两大竞争激励机制。',
    Grid_title_item12: '信誉数据宝库',
    Grid_text_item12: '通过币天消耗来控制刷信誉行为，每位开发者在社区中的历史成绩和行为、及作品发展的历史轨迹、评论家的评价行为等，都会被智能合约烙印在区块链之中，成为一个<span>可追溯的不可篡改</span>的信誉大数据库。',

    //#competitive
    competitive_title1: '竞争',
    competitive_title2: '优势',
    competitive_title_item1: '签约亿级流水产品',
    competitive_text_item1: '签约<span>亿级</span>月流水头部产品上线平台，社区上线之初即有<span>十数款</span>商业盈利成熟大作。',
    competitive_title_item2: '深厚业内资源',
    competitive_text_item2: '深耕游戏行业核心研发和运营<span>十数年</span>，拥有深厚游戏行业资源、经验和互联网深度人脉。',
    // competitive_text_item2: '深耕游戏行业核心研发和运营十数年，VR国家标准编写成员单位。微软中国、东方明珠携手共建游戏开发者扶持计划。', 
    competitive_title_item3: '即点即玩HTML5 2.0',
    competitive_text_item3: '<span>转化现有</span>高品质重度原生游戏为“免下载免安装即点即玩”入口形态。无限流量、千兆4G、5G<span>重大利好</span>接踵而来，<span>移动宽带</span>互联网时代的游戏入口新标准！',
    competitive_title_item4: '国际水平的游戏引擎',
    competitive_text_item4: '国际水平的游戏引擎制作工具Bcreator.io。',
    // competitive_text_item4: '成熟可用的引擎BCreator，已经有近4000注册用户的种子社区。BCreator是VR中国国家标准编写成员单位。',
    competitive_title_item5: '成熟直播软件系统',
    competitive_text_item5: '社区内建游戏直播，极大提高社区活跃度和黏着度。',
    competitive_title_item6: '智能合约的图形化免编程编制工具',
    competitive_text_item6: '图形NLP化的<span>免编程</span>智能合约编制工具AISC，摆脱只能由程序员编写智能合约的桎梏，回归传统文字合同编制的便利性。AISC得到<span>NEO</span>鼎力支持。',//??

    //#price
    price_title1: '产品',
    price_title2: '展示',

    price_item1: '亿元月流水《三国志2017》',
    price_item2: '千万月流水《全民乐舞》',
    price_item3: '无双经典致敬《真三国战纪》',
    price_item4: '现金流游戏《来啊捕鱼》',
    price_item5: '沙特Edu-game《عالم أريب》',
    price_item6: '单月服5万美金《初代吸血鬼》',
    price_item7: '《Beauty and the beast》',
    price_item8: '像素IO游戏《我的坦克》',
    price_item9: 'H5《クリプトアイランド 》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5《直播秀场百人德州》',
    price_item12: '月流水千万《幻想学园》',

    //#team
    team_title: '团队',
    team_title_intro: '介绍',
    team_title1: '主创团队',
    team_title2: '顾问团队',
    team_title3: '投资机构',

    team_name_item1: 'Ali Dagli',
    team_text_item1: '加利福利亚伯克利分校金融学博士，数字媒体领域资深投资人和金融战略顾问。在GCA Savvian副总裁，运作了日本社交巨头Gree 2.1亿美金收购Funzio、Saban Brands收购The Playforge等著名案例。自2013年起对区块链金融深入研究和实践。',
    team_name_item2: 'Thomas Lindgren',
    team_text_item2: 'Western University MBA。游戏行业资深人士，曾任瑞典游戏公司Stardoll担任CEO，Fatshark AB 制作人。',
    team_name_item3: 'Oliver Wu',
    team_text_item3: '宾夕法尼亚大学计算机博士，著名经典文字MUD《Three Kindgoms》巫师，《Warhammer: end times》MMO制作人。曾担任新加坡互动媒体中心负责人 ，负责青奥会虚拟现实世界的开发和运营。担任中青宝前海外总裁。',
    team_name_item4: 'Abdullah Konash',
    team_text_item4: '美国哈佛大学音乐艺术理论研究员。沙特阿拉伯游戏设计和开发领域的先驱，在游戏领域有九年的工作经验，并且渴望领导沙特阿拉伯游戏行业的发展。曾任Hako Games，Ranam制作人。',
    // team_name_item4: '董浩',
    // team_text_item4: '上海交通大学软件硕士，完美世界研究中心工程师，VR黄埔军校著称的中视典原CTO，BCreator创始人。15年游戏行业经验，多款盈利商业大作。自2014年既着手研究区块链在游戏行业的应用。',
    team_name_item5: '冯涛',
    team_text_item5: '联创永宣董事长。新浪等众多著名商业传奇缔造者，与沈南鹏等入选福布斯中国2017最佳创投人前三甲。区块链领域早期既支持了INB、OK 、 NEO 、 BigONE、Beechat等项目。',
    team_name_item6: 'Frank Liu',
    team_text_item6: '新加坡南洋理工大学博士后研究员，拥有多项专利知识产权，数学功底深厚。对三维图形学、密码学、点对点通讯、区块链共识机制、深度学习有深入研究。',
    team_name_item7: '易理华',
    team_text_item7: '优领资本创始合伙人，INBlockchain（硬币资本）创始合伙人。曾投资量子链、唯链、雷盈、BigONE等30余个区块链项目，涵盖量化基金、区块链母基金、代码审计、交易所等领域。',
    team_name_item8: '谭群钊',
    team_text_item8: '华东理工大学，北京大学EMBA。丰厚资本创始人，盛大联合创始人，曾任盛大游戏董事长兼首席执行官，为盛大游戏、中国游戏产业的发展做出了巨大贡献。',
    team_name_item9: '李翀',
    team_text_item9: '天使投资人，点亮资本发起人，PPTV联合创始人。专注于移动互联网、区块链等领域，涌现出布比区块链、三迪建科、波奇、P2联合办公等一大批优秀项目。',
    team_name_item10: '刘嘉陵（巨蟹）',
    team_text_item10: '国内早期区块链项目布道者和投资者，比特创业营创始成员，比特股和以太坊项目早期参与者，比特股理事会理事、YOYOW团队成员、ATMatrix智能矩阵天使投资人。',
    team_name_item11: '金鹏',
    team_text_item11: '复旦大学哲学博士，师从中共中央政治局常委王沪宁教授。前盛大网络高级副总裁，上海联创管理合伙人，无穹创投创始人，在游戏、娱乐、数字金融及营销领域投资了大量新兴企业。',
    team_name_item12: 'Lee Hills',
    team_text_item12: '电子游戏业务的企业家和资深顾问，擅长新兴行业，专注于区块链和金融科技领域。曾是SolutionsHub Limited创始人，Oliver Charles Sports Management联合创始人。',
    // team_name_item10: '毛杰',
    // team_text_item10: '知名天使投资人，原上海钢联（300226）副总及董事。现为自由投资人，专注于区块链、无人机、大数据领域，投资了多个行业的明星项目。',
    // team_name_item12: '朱科敏',
    // team_text_item12: '西南财经大学金融学博士，中共中央党校法学硕士。东海证券董事长、总裁。早期便深入研究区块链金融领域应用。',
    team_support_item1: '<span>G</span>AME.<span>F</span>UND是NEO生态的<a>dApp</a>',
    team_support_item2: 'AISC获得',
    team_support_item3: '鼎力支持',

    //#contact
    contact_we: '联系我们',
    contact_broadcast_group: '公告地址：',
    contact_chat_group: '聊天群地址：',
    contact_mail: '邮箱地址：',
    broadcast_group: '广播群',
    chat_group: '聊天群',

    //#community
    community_title1: '社区',
    community_title2: '生态',
    community_img_title: 'GF通证分配方案',
    community_title_item1: '社区投放 20%',
    community_text_item1: '20%的GF直接投放社区运作',
    community_title_item2: '社区内容激励 45%',
    community_text_item2: '45%的GF用于社区内容激励，维护社区的高品质良性运作。由智能合约按社区细则客观执行激励。',
    community_title_item3: '早期天使 5%',
    community_text_item3: '5%的GF为早期天使持有，有了他们的支持，社区才有现在的基础，社区运行一年内锁定。',
    community_title_item4: '生态基础激励 15%',
    community_text_item4: '15%的GF用于激励GAME.FUND生态基础建设者，以及合作伙伴，用以夯实生态体系。',
    community_title_item5: '主创团队 15%',
    community_text_item5: '15%的GF为主创团队持有，社区运行一年内锁定。',
        
    // total_content_item1: 'GF（GAME.FUND）是本社区通证，拥有GF是社区成员的标志。GF基于NEO区块链记账，总量5亿个，可精确到10<sup>-8</sup>，永不增发。',
    total_content_item1: 'GF（GAME.FUND）是本社区通证，拥有GF是社区成员的标志。GF基于NEO区块链记账，总量50亿个，可精确到10<sup>-8</sup>，永不增发。',
    total_content_item2: '第一期私募5% ，2018年03月08号截止私募白名单登记，2018年02月15号前为早鸟期。',
    total_content_item3: '2018年05月31号前GF通证通过智能合约转移到各投资人的NEO地址，两周内上交易所。',

    community_video_title: '社区运作',
    video_tag_tip: '您的浏览器不支持video标签',
    community_video_text1: '是不有点烧脑？没事，您看这一段就能明白',
    community_video_text2: '简单的说，社区各角色价值流转行为都以GF为流通凭证，币天和币天担保机制鼓励用户持有GF和避免刷信誉及排名。社区按不同比例收取游戏众筹和游戏发行的分成，此分成收入用作社区建设和维护外，至少50%按GF持有比例定期分配到对应地址。随着社区的推广扩大，越来多用户加入社区，GF通证的升值是必然的',

}

//-----------------------------------------英文版
var en = {
    //index.html
    navigation_item1: 'Introduction',
    navigation_item2: 'Background',
    navigation_item3: 'Solution',
    navigation_item4: 'Advantage',
    navigation_item5: 'Team',
    navigation_item6: 'Ecology',
    registration_item: 'Join whitelist',

    sequence_item1: 'The community based on global decentralization blockchain that of the people, by the people, for the people.',
    sequence_item2: 'White Papers',
    sequence_item2_first: 'White Papers',
    sequence_item2_second: '中文',
    sequence_item2_third: '日語',
    sequence_item2_fourth: 'JOIN OUR TELEGRAM',

    //#industry_status
    industry_status_feature: 'FEATURE',
    industry_status_item1: 'The real return of power to the people, establishing a positive competition incentive mechanism of democratically evaluating works by player for the two primary kinds of community content, game works and work comments. Transparent and fair, no one can control it.',
    industry_status_item2: 'Grasp the <span>original source</span>. Mature game crowdfunding, make BCreator.io and hatchery for Chinese and Japanese Independent developer, help developer realize dream. GAME.FUND contracts with original works and excellent team, reserve content resources strategic high ground.',
    industry_status_item3: '<span>Click it to play without download and install</span>. Convert existing large and high quality <span>native</span> games to be <span>Click it to play</span> H5(Instant APP) mode to reduce promotion cost. Unlimited traffic Gigabit 4G, 5G big benefit times come one after another. New entrance standard of <span>mobile broadband</span> internet era.',
    industry_status_item4: 'Reputation database. The historical behavior of developers and critics will be  imprinted in the block chain, traceability but can not be tampered with, become the large database of all kinds of  key decisions.',
    industry_status_item5: 'Platform SDK based on blockchain, to realize decentralize game account and right of digital property and perforation of across game trade.',

    industry_status_feature1: 'Virtual distributed structure',
    industry_status_feature2: 'High efficiency and low cost operation mode',
    industry_status_feature3: 'Decentralized structure',
    industry_status_feature4: 'Multi-node consensus mechanism',
    industry_status_feature5: 'Distributed ledger',

    //#service
    service_title1: 'INDUSTRY',//Industry background and problems
    service_title2: '&nbspBACKGROUND AND PROBLEMS',
    service_title_item1: 'The window period of seize the renaissance strategic high ground',
    service_text_item1: 'Chinese game is no longer an incremental market, but the era of retaining the user, the key is quality and playability, game <span>is returning to the beginning of heart</span>. The <span>genuine paid</span> consciousness of Chinese players is full of <span>rejuvenation</span>. The sun of game renaissance golden time is rising up. this is a window period to attract developer and fans, and snatch strategic high ground.',
    service_title_item2: 'The mode of game crowdfunding is ripe',
    service_text_item2: 'As of September 2017, the number of global game crowdfunding has reached 40000, raising a total of 900 million dollars, and 15 million users participate it. However, the <span>potential energy contradiction</span> of Chinese game industry is prominent: On the one hand, the <span>user number of pay</span> for outstanding game works have been very large. But on the other hand, potential team is <span>difficult to finance</span>, this potential energy contradiction urgently needs to be broken to <span>flood discharge</span> by a mode.',
    service_title_item3: 'Blockchain + Game Emerge',
    service_text_item3: 'There has been a lack of real projects in the area of blockchain, a lot of <span>empty words</span>. Excellent technology took the lead in the field of game once again. It focuses more players on the blockchain, and the investors of coin circle more accept the game projects. Global financing through digital currency is twice as the <span>traditional VC</span>, it is a strong <span>N<sub>2</sub>O accelerator</span> for crowdfunding.',
    
    //#portfolio
    portfolio_title1: 'SOLUTION',//Solution and implementation
    portfolio_title2: '&nbspAND IMPLEMENTING',
    portfolio_title_item1: 'Overall Solution',
    portfolio_title_item2: 'Make Game',
    portfolio_title_item3: 'Play Game',
    portfolio_title_item4: 'Communication',
    portfolio_title_item5: 'The Application of Blockchain',

    Grid_title_item1: 'Game Crowdfunding Community',
    Grid_text_item1: 'Community members invest in outstanding creative projects, obtain the return such as the work and the pre purchase right of related resources, even appreciation and so on, the success of crowdfunding is to reach or exceed the target amount, otherwise it will be returned to the sponsor.',
    Grid_title_item2: 'Tailored Create Tool',
    Grid_text_item2: 'Provides the only <span>international</span> high quality game engine in <span>Chinese</span> BCreator.io(The English version and japanese version will also be published.), it include graphical NLP of <span>programming-free</span> interactive logic module Director, greatly reduce the technical threshold, supply to developers to choose to create game.',
    Grid_title_item3: 'High Quality Game Distribution Platform',
    Grid_text_item3: 'Community attract excellent works and developers, growing popularity, and attract players through events, live broadcast, advertisement. After gathering a large number of players, they can further attract more works and excellent developers, form a <span>benign cycle</span>.',
    Grid_title_item4: 'Click It to Play HTML5 2.0',
    Grid_text_item4: 'realized convert the existing large and high quality <span>native</span> games to be <span>Click it toplay without download and install</span> H5(Instant APP) mode. Welcome unlimited traffic, Gigabit 4G、5G <span>mobile broadband</span> Internet new era, establishment of an epoch-making new form of game entry mode.',
    Grid_title_item5: 'High Level Comment',
    Grid_text_item5: 'Implementing <span>competition</span> and <span>incentive</span> mechanisms, and promoting content selecting review groups.',
    Grid_title_item6: 'Face the Opinion of Fans',
    Grid_text_item6: 'The player and the developer <span>communicate directly</span>, grind the work.',
    Grid_title_item7: 'IM System',
    Grid_text_item7: 'IM system, providing <span>instant messaging</span> services for users',
    Grid_title_item8: 'Live Broadcast System',
    Grid_text_item8: 'Effectively improve community <span>activity</span> and improve the <span>revenue</span> of game products.',
    Grid_title_item9: 'Interactive Community',
    Grid_text_item9: '<span>A fair and transparent</span> incentive mechanism based on blockchain. Players, developers, investors, critics and promoters interact within the community, their interaction is performed <span>by smart contracts</span>, and it will branded in the blockchain. Every member of the community will takes the initiative as a host to promote and build their own community.',
    Grid_title_item10: 'The SDK of Blockchain Access',
    Grid_text_item10: 'SDK based on blockchain, realize decentralization game account and the <span>right</span> of digital assets, and the <span>perforation</span> of cross-game <span>trade</span>, achieve one-click login of game, token settlement of platform, access of digital assets right verification and the perforation of trade.',
    Grid_title_item11: 'Conscientious Competition Incentive Mechanism',
    Grid_text_item11: 'The two quality competitive incentive mechanisms supported by blockchain. The excellence of the works and work comments UGC is entirely <span>determined by the player</span>, ensure the high quality of the community. The blockchain will guarantee <span>no one</span> including the founding team of the blockchain can <span>control and tamper with</span> the two competitive incentive mechanisms.',
    Grid_title_item12: 'Reputation Database Treasure',
    Grid_text_item12: 'Control click farming behavior through coindays consumption, the history score, behavior, develop historical track of works, and the commenting behavior of critics will branded in the blockchain by smart contract, become a reputation database that <span>traceability but can not be tampered with</span>. ',

    //#competitive
    competitive_title1: 'COMPETITIVE',//Competitive advantage
    competitive_title2: '&nbspADVANTAGE',
    competitive_title_item1: 'Sign with Billion Revenue Product',
    competitive_text_item1: 'Sign with product that has <span>billion</span> revenue, on the beginning of the community came online, it has <span>more than ten</span> commercial profits mature masterpiece.',
    competitive_title_item2: 'Deep Industry Resources',
    competitive_text_item2: '<span>More than ten years</span> of game development and operation experience, has deep game industry resource, experience and internet contacts.',
    competitive_title_item3: 'Click it to play HTML5 2.0',
    competitive_text_item3: '<span>Convert existing</span> high quality <span>native</span> game to achieve "Click it to play without download and install" mode. New entrance standard of <span>mobile broadband</span> internet era!',
    // competitive_text_item3: 'High quality original eco game to achieve “Click it to play without download”entrance form. unlimited traffic Gigabit 4G, 5G big benefit times come one after another. New entrance standard of mobile broadband internet era!',
    competitive_title_item4: 'Mature Game Production Tool Software Engine',//'Mature game production tool software engine'
    competitive_text_item4: 'Mature and available game make tool Bcreator.io',//
    competitive_title_item5: 'Mature Live Broadcast Software System',
    competitive_text_item5: 'Live games in the community, greatly improving the community activity and adhesion.',

    competitive_title_item6: 'Smart Contracts Graphical Programming-free Programming Tool',//??
    competitive_text_item6: 'programming-free smart contracts programming tool AISC, return the convenience of tradition that write contract by words. AISC got the great help of <span>NEO</span>.',//??

    //#price
    price_title1: 'PRODUCT',//Product display
    price_title2: '&nbspDISPLAY',

    price_item1: 'The monthly revenue of 《三国志2017》 reached 100 million yuan',
    price_item2: 'The monthly revenue of 《全民乐舞》 reached ten million yuan',
    price_item3: '《真三国战纪》 tribute to the classic works',
    price_item4: 'Cash flow game 《来啊捕鱼》',
    price_item5: 'Saudi Arabia Edu-game 《عالم أريب》',
    price_item6: '《初代吸血鬼》‘s  monthly revenue reached 50000 dollars of each server',
    price_item7: '《Beauty and the beast》',
    price_item8: 'Pixel IO game 《我的坦克》',
    price_item9: 'H5 《クリプトアイランド》',
    price_item10: '《梦幻3D》',
    price_item11: 'H5 《直播秀场百人德州》',
    price_item12: '《幻想学院》 monthly revenue reached ten million yuan',

    //#team
    team_title: 'TEAM',//Team introduction
    team_title_intro: '&nbspINTRODUCTION',
    team_title1: 'The Main Team',
    team_title2: 'Consultant Team',
    team_title3: 'Sponsors',

    team_name_item1: 'Ali Dagli',
    team_text_item1: 'Ph.D. in Finance, Berkeley, California, Senior investor and financial strategist in the Digital Media area. Vice President of GCA Savvian, he operate the Japanese social giant Gree, and he has use 2.1 billion acquisition Funzio, Saban Brands acquisition The Playforge and other famous case. Since 2013, he conducted in-depth studies and practices on blockchain finance.',
    team_name_item2: 'Thomas Lindgren',
    team_text_item2: 'Western University MBA. senior personage on game industry, he used to be CEO of the Swedish game company Stardoll, the productor of Fatshark AB.',
    team_name_item3: 'Oliver Wu',
    team_text_item3: 'Ph.D., University of Pennsylvania, the productor of famous classic text MUD “Three Kindgoms wizard”, MMO game "Warhammer: end times ". he used to be responsible person in Singapore Interactive Media Center, responsible for the development and operation of the virtual reality world of the Youth Olympic  Games. As a former overseas president of Zhongqingbao.',
    team_name_item4: 'Abdullah Konash',
    team_text_item4: 'Harvard University, music art theory researcher. He has 9 years experience in the game industry, and  longs to lead the development of the Saudi Arabia’s game industry. He was the producer of Hako Games, Ranam.',
    // team_name_item4: 'Dong Hao',
    // team_text_item4: 'Master of software of Shanghai Jiao tong University, engineer of Perfect World research center, the former CTO of VRSTANDARD which be called VR Huangpu Military Academy, the founder of BCreator. He has 15 years of experience in the game industry, producing a number of profitable commercial masterpiece Division, CT  known as the CTO, BCreator Chong. From 2014, he started to study the application of blockchain in the game industry.',
    team_name_item5: 'Feng Tao',
    team_text_item5: 'The chairman of Lianchuang Yongxing. The creator of Sina and many other famous business legend, he was selected  to Forbes China 2017 best venture capital Top three with Shen Peng and others. In the early period of Blockchain field he had supported INB, OK, NEO, BigONE, Beechat and other projects.',
    team_name_item6: 'Frank Liu',
    team_text_item6: 'The postdoctoral researcher of Singapore Nanyang Technological University, he has a number of patents Intellectual property and very deep mathematics foundation. He also has deep research on 3D graphics, crytography, peer-to-peer communications, blockchain consensus mechanism.',
    team_name_item7: 'Yi Lihua',
    team_text_item7: 'Founding Partner of Youling Capital and INBlockchain (Coin Capital). Had invested in quantum chain, VeChain, RadarWin, BigONE more than 30 blockchain projects, covering quantitative funds, blockchain matrix Gold, code audit, exchange and other fields.',
    team_name_item8: 'Tan Qunzhao',
    team_text_item8: 'The EMBA of East China University of Science and Technology, Peking University. The founder of Fenghou investment management company and co-founder of Shanda, he used to be the chairman and chief executive official of Shanda, made a huge contribution for the Shanda game and the Chinese game industry.',
    team_name_item9: 'Li Chong',
    team_text_item9: 'Angel Investor, the sponsor of Liangdian Capital, Co-Founder of PPTV. Focus on the mobile Internet, blockchain and other fields, emerge Bubi blockchain, SandiJianke, Boqi, P2 joint office and a large number of outstanding project.',
    team_name_item10: 'Liu Jialing（Cancer）',
    team_text_item10: 'Evangelist and investor in early national blockchain project, founding members of Bit participants and  early participants of Ethereum Project, member of Bitshares council, member of YOYOW team、the investor of ATMatrix Smart matrix.',
    team_name_item11: 'Jin Peng',
    team_text_item11: 'Ph.D. of Fudan University, his mentor is Political Bureau of the CPC Central Committee Standing Committee Professor Wang Huning. Former Senior Vice President of Shanda Network, the partner of Shanghai Lianchuang Management company, Founder of Wuqiongchuangtou, he invested in a large number of emerging industries in games, entertainment, digital Finance and marketing.',   
    team_name_item12: 'Lee Hills',
    team_text_item12: 'The entrepreneurs and senior adviser of the computer game, he is good at emerging industry, focus on the field of blockchain and financial technology. He is the founder of SolutionsHub Limited and the co-dounder of Oliver Charles Sports Management.',
    // team_name_item10: 'Mao Jie',
    // team_text_item10: 'Well-known angel investors, the former vice president and chairman of Shanghai Steel (300226). Now he is a  freelance investor, focusing on blockchain, drone, big data area, invest in a number of industry star project.',
    // team_name_item12: 'Zhu Kemin',
    // team_text_item12: 'Ph.D. of Southwest University of Finance and Economics,  law master of CPC Central Party School. Chairman and president of Donghai Securities. He deep studied the financial applications of blockchain in early times.',
    team_support_item1: '<span>G</span>AME.<span>F</span>UND is the <a>dApp</a> of NEO ecology',
    team_support_item2: 'AISC got',
    team_support_item3: 'great support',

    //#contact
    contact_we: 'Contact Us',
    contact_broadcast_group: 'Notice Address：',
    contact_chat_group: 'Chat Address：',
    contact_mail: 'E-mail：',
    broadcast_group: 'Broadcast Group',
    chat_group: 'Chat Group',
  
    //#community
    community_title1: 'COMMUNITY',//Community Ecology
    community_title2: '&nbspECOLOGY',
    community_img_title: 'GF Token Distribution Plan',
    community_title_item1: 'Community Launch 20%',
    community_text_item1: '20% of GF is launched directly to the community',
    community_title_item2: 'Community Content Incentive 45%',
    community_text_item2: '45% of GF is used to community content incentive, maintaining and improving the high quality of community content. The incentive will be objectively implemented by smart contract according to the community rules',
    community_title_item3: 'Early Angel 5%',
    community_text_item3: '5% of GF is held by early angel, with their support, the community has the foundation of the present, and it will locked within one year of community operation. ',
    community_title_item4: 'Ecology Basis Incentive 15%',
    community_text_item4: '15% of GF is used to motivate GAME.FUND ecological foundation builders and partners to tamp the ecosystem.',
    community_title_item5: 'The Main Team 15%',
    community_text_item5: '15% of GF is held by the main team, and it will locked within one year of community operation.',

    total_content_item1: 'GF the token of GAME.FUND is the community status symbol. It ledgers based on the NEO blockchain. Total amount of GF is 5 billion,accurate to 10<sup>-8</sup>，the circulation will never increase.',
    total_content_item2: '5% GF for the first private equity placement. This phase of private placement whitelist registration will end on March 8 2018. Before February 15 2018 is the early bird period. ',
    total_content_item3: 'Before May 31 2018, the GF token will transfer to the NEO address of all investors, and it will listed on exchange within two weeks.',

    community_video_title: 'Community Operation',
    video_tag_tip: 'Your browser does not support video tags',
    community_video_text1: 'Is not a bit brain burning? All right, Please read this passage',
    community_video_text2: 'Simply put, the role of the community value of the transfer of behavior are based on GF. Mechanism of coin days and coin days guarantee to encourage users to keep GF and avoid brush credit and ranking. The community charge income of game crowdfunding and game distribution at different rates. One part of the income used for community constraction and maintenance, at least 50% regularly assigned to the corresponding address according to the GF holding ratio. With the expansion of the community by promotion, more and more users to join the community, GF\'s value will go up.',
}


//-----------------------------------------日文版
var ja = {
    //index.html
     navigation_item1: '前書き',
    navigation_item2: '背景と問題',
    navigation_item3: '解決方案',
    navigation_item4: '競争優位',
    navigation_item5: 'チーム紹介',
    navigation_item6: 'コミュニテイ生態',
    registration_item: 'ホワイトリストに加入する',

    sequence_item1: 'ブロックチェーンに基づいたのグローバルな分権化の人民所有人民管理人民享有のコミュニティ',
    sequence_item2: 'ホワイトペーパー',
    sequence_item2_first: 'ホワイトペーパー',
    sequence_item2_second: '中文',
    sequence_item2_third: 'ENGLISH',
    sequence_item2_fourth: 'チャートグループに加入する',

    //#industry_status
    industry_status_feature: '特徴',
    industry_status_item1: '本当に政治を人民に返す、プレイヤーが作品と二つコミュニティの内容を民主的に評論するという健康的な競争メカニズムを確立する、透明公正、誰にも<span>操られないのメカニズムです</span>',
    industry_status_item2: '<span>創作のソースを掴む</span>。成熟したのゲームクラウドファンデイングパターン、チャイニーズと日本語の開発者に対するのテーラードゲーム制作ツールエンジンBCreator.ioとインキュベーションサイトなどを提供して、開発者の夢の始まりを助けます。GAME.FUNDコミュニティはオリジナル作品と優秀なチームとサインして、コンテンツリソース戦略高地を予備します。',
    industry_status_item3: 'ダウンロード不要<span>クリックして遊べます</span>の新しい入口タイプ。<span>現在の</span>重度原生のゲームを“ダウンロードとインストール不要クリックして遊べます”の入口タイプに転換する。ゲームプロモーションのコストを下げります、<span>モバイルインターネットのブロードバンド</span>時代のHTML5 2.0に応じして、無制限のトラフィック、ギガビット4G、5Gという<span>高収益</span>時代次来る、確実に業界の新標準になります。',
    industry_status_item4: 'レビュテーション<span>データベース</span>。開発者、批評家の歴史行為はスマート契約がブロックチェーンに<span>記録</span>されます、それにこの記録が遡ることができますが、改ざんできないです、あらゆる種類の意思決定に依存するの大規模なデータを形成できます。',
    industry_status_item5: 'ブロックチェーンに基づいたのSDK、分権化ゲームアカウントとデジタル財産の<span>確認権利</span>、そしてゲームを越えるの<span>取引</span>の貫通を実現します。',

    industry_status_feature1: '仮想分散構造',
    industry_status_feature2: '高効率と低コストの運営モード',
    industry_status_feature3: '分権化の構造',
    industry_status_feature4: 'マルチノードコンセンサスメカニズム',
    industry_status_feature5: '分散式記帳',

    //#service
    service_title1: '業界',
    service_title2: '背景と問題',
    service_title_item1: '戦略高地を占領するのウインド時期',
    service_text_item1: '中国語ゲームは既にユーザーを増える市場ではない、ユーザーを残すの時代です、品質と遊ぶが重要です、今ゲームは<span>初志へ戻っています</span>、チャイニーズのプレイヤーの<span>著作権</span>支払いの認識が完全に<span>目覚めました</span>、チャイニーズゲームの文芸復興の黄金時代の朝日が昇っています。今は低コストで開発者とファンを引きつけって、戦略高地を占領するの稀な<span>ウインドウ時代</span>です。',
    service_title_item2: 'ゲームクラウドファンでイングパターンが確認されました',
    service_text_item2: '2017年9月までに、世界中4万以上のゲームクラウドファンでイングプロジェクトがあります、合計9億ドル、1500万のウーザーが投資を参加しました。対照的に、中国語ゲーム業界には<span>潜在的な衝突</span>が目立つです：一方、優秀なゲーム作品に<span>支払う</span>のウーザー群体は巨大ですが、潜在力があるのチームは<span>資金調達が難しい</span>と感じています、この衝突は緊急的にあるモデルによって<span>壊される</span>差し迫った必要があります。',
    service_title_item3: 'ブロックチェーン+ゲームが現す',
    service_text_item3: 'ブロックチェーン領域には実現できるのプロジェクトが不足で、<span>空論</span>が多い。優秀な新技術はまたゲーム領域に応用しました、ブロックチェーンに重点を置くプレイヤーが増やした、コインサークルの投資者がゲームプロジェクトを受けるの度合いも高くなりました。世界中ブロックチェーンデジタル通貨で融資するの金額は<span>伝統VCの二倍になりました</span>、これも私たちのクラウドファンデイングパターンの<span>N<sub>2</sub>Oスーパーアクセラレータです</span>。',
    
    //#portfolio
    portfolio_title1: '解決方案',
    portfolio_title2: 'と実現',
    portfolio_title_item1: '全体の方案',
    portfolio_title_item2: 'ゲーム制作',
    portfolio_title_item3: 'ゲームを遊ぶ',
    portfolio_title_item4: 'ゲームの交流',
    portfolio_title_item5: 'ブロックチェーンの応用',

    Grid_title_item1: 'ゲームブロックチェーンエリア',
    Grid_text_item1: 'クラウドファンデイングを通じて優秀なアイデアプロジェクトに投資する、作品と関連資産の先行予約購買権、ひいては切り上げなどのリターンを獲得できる、目標金額に達するや超えるのはクラウドファンデイングの成功条件です、そうでなければ、全ての金額は援助者に帰還します。',
    Grid_title_item2: 'テーラーメイド創作ツール',
    Grid_text_item2: '<span>チャイニーズ</span>の唯一の<span>国際</span>標準の高品質<span>ゲームエンジン</span>BCreator.ioを提供する（英語版と日本語版もリリースされます）、グラフィックスNLP化の<span>プログラミング不要</span>のインタラクティブぶロジックモジュールDirectorが技術要求を下げる、開発者のゲーム制作に利便性をもたらす。',
    Grid_title_item3: '高品質ゲーム配信プラットフォーム',
    Grid_text_item3: 'コミュニティが優れた作品と開発者を引きつけって、人気を集まる。イベント、ライブと広告などの方式デプレイヤーを引きつける。大量なプレイヤーがあった後、またもっと多くの作品と開発者を引きつける、<span>好循環</span>を形成できます。',
    Grid_title_item4: 'クリックで遊べますのHTML5 2.0',
    Grid_text_item4: '大きな高品質<span>重度原生</span>ゲームの”<span>ダウンロードとインストール不要クリックで遊べます</span>”HTML5化を実現する。無制限のトラフィック、ギガビット4G、5G<span>モバイルインターネット</span>のブロードバンド時代を迎えて、画期的な新しいゲーム入口パターンを立てます。',
    Grid_title_item5: '高レベルのコメント',
    Grid_text_item5: '<span>競争</span>と<span>インセンティブ</span>のメカニズムを実施する、コンテンツスクリーニング批評家グループを促進します。',
    Grid_title_item6: 'ファンの意見に直面する',
    Grid_text_item6: 'プレイヤーと開発者<span>直接に交流して</span>、作品を磨きます。',
    Grid_title_item7: 'IMシステム',
    Grid_text_item7: 'IMシステム、ウーザーに<span>インスタントメッセージングダービス</span>を提供します。',
    Grid_title_item8: 'ライブシステム',
    Grid_text_item8: '効果的にコミュニティの<span>活躍度</span>とゲーム産品の<span>収益</span>を高めます。',
    Grid_title_item9: 'インタラクティブコミュニティ',
    Grid_text_item9: 'ブロクチェーンに基づいたの<span>公正透明</span>的なインセンティブメカニズム。プレイヤー、開発者、投資家、批評家、プロモーターはコミュニティの中で交流できます、彼らの行動は<span>スマート契約</span>によって実行されて、ブロクチェーンに<span>記録</span>されます。全てのメンバーは主人としての態度でコミュニティを促進と構築します。',
    Grid_title_item10: 'ブロクチェーンアクセスSDK',
    Grid_text_item10: 'ブロクチェーンに基づいたのSDK、分権化のゲームアカウントとデジタル財産の<span>確認権利</span>、ゲームを越えるの<span>取引の貫通</span>を実現します。そしてゲームを越えるのオンクリックログイン、GFの決済手段、デジタル財産のアクセスと取引の貫通を実現します。',
    Grid_title_item11: '健全な競争インセンティブメカニズム',
    Grid_text_item11: 'ブロクチェーンに支えたの二つ健全な競争インセンティブメカニズム。作品と作品コメントUGCが優れたかどうか、完全<span>にプレイヤーで決めます</span>、コミュニティの高品質を確保します。ブロクチェーンは創業チームを含むの全ての人と勢力がこの二つ競争インセンティブメカニズムを<span>制御と改ざんすることができない</span>ことを保障します。',
    Grid_title_item12: 'レビュテーションデータベース',
    // Grid_text_item12: 'コインでいーの消費を通じてクリックファーミング行為を制御します、全ての開発者のコミュニティ歴史成績、行為、作品発展の軌道、批評家の評価行為などはスマート契約をブロクチェーンに記録されます、遡ることができるが改ざんできないの巨大なデータベースを形成できます。',
    Grid_text_item12: 'コインデーの消費を通じてクリックファーミング行為を制御します、全ての開発者のコミュニティ歴史成績、行為、作品発展の軌道、批評家の評価行為などはスマート契約をブロクチェーンに記録されます、<span>遡ることができるが改ざんできない</span>の巨大なデータベースを形成できます。',

    //#competitive
    competitive_title1: '競争',
    competitive_title2: '優位',
    competitive_title_item1: '売上億円の作品と契約する',
    competitive_text_item1: '売上<span>億円</span>の作品と契約して第一部作品としてプラットフォームにリリース、コミュニティ運営の初期は<span>何十部</span>商業利益の作品があります。',
    competitive_title_item2: '深い行内資源',
    competitive_text_item2: '<span>十年以上</span>のゲームコア研究と運営の経験があります、厚いゲーム業界資源、経験とインターネット人脈があります。',
    competitive_title_item3: 'クリックで遊べますのHTML5 2.0',
    competitive_text_item3: '<span>現在の</span>高品質重度原生のゲームを“ダウンロードとインストール不要クリックして遊べます”の入口タイプに<span>転換</span>する。<span>モバイルブロードバンドインターネット</span>時代のゲーム入口の新標準！',//
    competitive_title_item4: '国際レベルのエンジン',
    competitive_text_item4: '国際レベルのゲームエンジン制作ツールBCreator.io',
    competitive_title_item5: '成熟したライブソフトシステム',
    competitive_text_item5: 'コミュニテイの中にゲームライブできます、大幅にコミュニテイの活躍度と粘着性を増加します。',
    competitive_title_item6: 'スマート契約のグラフィックスプログラミング不要のツール',
    competitive_text_item6: 'グラフィックスNLP化<span>のプログラミング不要</span>スマート契約ツールAISC、伝統の文字契約の利便性に戻ります。AISCが<span>NEO</span>の完全なサポートを得ました。',//??
    //#price
    price_title1: '製品',
    price_title2: 'の展示',

    price_item1: '月売上億円月『三国志2017』',
    price_item2: '月売上千万『全民乐舞』',
    price_item3: '無双に敬意を表する『真三国战纪』',
    price_item4: 'キャッシュフローゲーム『来啊捕鱼』',
    price_item5: 'サウジアラビアEdu-game『عالم أريب』',
    price_item6: '単月サーバー5万ドル『初代吸血鬼』',
    price_item7: '『Beauty and the beast』',
    price_item8: 'ピクセルIOゲーム『我的坦克』',
    price_item9: 'H5『クリプトアイランド』',
    price_item10: '『梦幻3D』',
    price_item11: 'H5『直播秀场百人德州』',
    price_item12: '月売上千万『幻想学园』',
    //#team
    team_title: 'チーム',
    team_title_intro: '紹介',
    team_title1: '主要製作チーム',
    team_title2: '顧問チーム',
    team_title3: 'スポンサー',

    team_name_item1: 'Ali Dagli',
    team_text_item1: 'カリフォルニア州バークレー校の財務担当博士、デジタルメデイア及び財務戦略コンサルタントの上級投資家です。GCA Savvian副社長。日本の社交ボスGree2.1億ドルでFunzioを買う、Saban BrandsがThe Playforgeを買うなど有名なケースを操作しました。2013年以後、ブロクチェーンファイナンスに調査と行動を行われました。',
    team_name_item2: 'Thomas Lindgren',
    team_text_item2: 'Western University MBA。ゲーム業界のベテランです。スウエーデンゲーム会社StardollのCEOとFatshark ABのプロデューサーを担当したことがあります。',
    team_name_item3: 'Oliver Wu',
    team_text_item3: 'ペンシルバニア大学のコンピュータ博士、有名な文字MUD『Three Kindgoms』『sorcerian』『Warhammer: end times』のプロデューサーです。シンガポールインタラクティブメデイアセンターの責任者、ユーサオリンピックのバーチャルり有りティワールドの開発と運営を担当したことがあります。中青宝の前海外総裁です。',
    team_name_item4: 'Abdullah Konash',//???
    team_text_item4: 'ハーバード大学の音楽芸術理論研究者。サウジアラビアのゲームデサインと開発分野のパイオニアです。ゲーム業界で9年の経験があります。サウジアラビアゲーム業界の発展をリードするの望みがあります。Hako GamesとRanamのプロモーターを担当したことがあります。',
    // team_name_item4: '董浩',
    // team_text_item4: '上海交通大学のソフトウエアのマスター、软件硕士，完美世界研究センターのエンジニア、VRワンパオ軍事アカデミーと呼ばれるの中視典の前CTO、BCreatorの創業者。15年のゲーム業界経験があります、様々な商業利益の傑作があります。2014年以後はブロクチェーンがゲーム業界の応用を研究始めます。',
    team_name_item5: '馮涛',
    team_text_item5: '联創永宣の理事長。新浪など有名な商業伝説のクリエイターです。沈南鹏などと共にフォーブスチャイナの最高のベンチャーキャピタリストの前3位に入りました。初期のブロックチェーン分野で、彼がINB、OK、NEO、BigONE、Beechatなどのプロジェクトを支持しました。',
    team_name_item6: 'Frank Liu',
    team_text_item6: 'シンガポール新加坡南陽工科大学ポストドクター研究員、多数の特許知的財産を所有します、数学の基礎が深い。3Dフラフィックス、暗号、ポイント・アンド・ポイント通信、ブロックチェーンコンセンサスメカニズムと深い学習に深い研究があります。',
    team_name_item7: '易理華',
    team_text_item7: '優領資本とINBlockchain（コイン資本）の創業パートナーです。量子链、唯链、雷盈、BigONEなど30個以上のブロックチェーンプロジェクトを投資しました。量化ファンド、ブロックチェーンマザーファンド、コード監査、取引所などの分野をカバーします。',
    team_name_item8: '譚群釗',
    team_text_item8: '華東工科大学、北京大学のEMBA。豊厚資本の創業者、盛大の共同設立者、盛大ゲームの前理事長游戏董事长兼最高経営責任者、盛大ゲームと中国ゲームの発展に巨大な貢献をしました。',
    team_name_item9: '李翀',
    team_text_item9: 'エンジェル投資家、点亮資本のプロモーター、PPTVの共同設立者、モバイルインターメット、ブロクチェーンなどの領域に焦点を当てる、布比ブロクチェーン、三迪建科、波奇、P2合同オフィスなど優れたプロジェクトが出現しました。',
    team_name_item10: '劉嘉陵（巨蟹）',
    team_text_item10: '国内初期のブロックチェーンのエバンジェリストと投資家、ビット起業家キャンプの創設メンバー、ビットシェアとエテリアムの初期参加者、ビットシェア理事会の理事、YOYOWチームのメンバー、ATMatrixスマートマトリックスのエジェル投資家。',
    team_name_item11: '金鹏',
    team_text_item11: '復旦大学の哲学博士、CPC中央委員会政治局常任委員会王沪寧教授の学生です。盛大ネットワークの前上級副社長、上海联創管理のパートナー、无穹投の創業者です。ゲーム、エンターテイメント、デジタルファイナンス及びマーケテイングの分野で大量の新興企業を投資しました。',
    team_name_item12: 'Lee Hills',
    team_text_item12: '電子ゲーム業界の企業家とベテラン顧問。新興業界が得意です、ブロックチェーンと金融科学技術分野に専念します。SolutionsHub Limitedの創始者とOliver Charles Sportsの共同創設者です。',
    // team_name_item10: '毛傑',
    // team_text_item10: '有名なエンジェル投資人、上海钢联（300226）の前副社長と取締役。現在は自由投資家、ブロクチェーン、UAV、ビッグデータの分野に焦点を当てます、いくつの業界のスタープロジェクトを投資しました。',
    // team_name_item12: '朱科敏',
    // team_text_item12: '西南財政経済大学の金融博士、CPCセントラルパーティスクールの法律のマスター。東海証券の理事長、社長。东海证券董事长、总裁。ずっと前に金融分野におけるブロクチェーンの活用を研究します。',
    team_support_item1: '<span>G</span>AME.<span>F</span>UNDはNEOエコロジーの<a>dApp</a>です',
    team_support_item2: 'AISC獲得 ',
    team_support_item3: '完全なサポート',

    //#contact
    contact_we: 'お問い合わせ',
    contact_broadcast_group: '公告アドレス：',
    contact_chat_group: 'チャートグループアドレス：',
    contact_mail: 'メールアドレス：',
    broadcast_group: '放送グループ',
    chat_group: 'チャートグループ',

    //#community
    community_title1: 'コミュニテイ',
    community_title2: 'エコロジー',//生態
    community_img_title: 'GF通証配給方案',
    community_title_item1: 'コミュニテイ 20%',
    community_text_item1: '20%のGFがコミュニテイ運営に割り当てる。',
    community_title_item2: 'コミュニテイコンテンツインセンティブ45%',
    community_text_item2: '45%のGFがコミュニテイコンテンツインセンティブとして、コミュニテイコンテンツの高品質を維持と改善します。スマート契約がコミュニティルールに従ってインセンティブを客観的に実行します。',
    community_title_item3: '初期エンジェル 5%',
    community_text_item3: '初期エンジェルが5%のGFを持ちます、彼らのサポートでコミュニティが現在の基礎があります、この部分がコミュニティ運行の一年内にロックされます',//
    community_title_item4: 'エコロジー基礎インセンティブ 15%',
    community_text_item4: '15%のGFはGAME.FUNDエコロジー基礎の建設者とパートナーを激励するために用いられます，エコロジー体系を固めます。',
    community_title_item5: '主要創作チーム15%',
    community_text_item5: '主要創作チームが15%のGFを持ちます、この部分がコミュニティ運行の一年内にロックされます',
        
    total_content_item1: 'GF（GAME.FUND）は本コミュニティの通証、拥有GFを持っているのはコミュニティメンバーのマークです。GFの記帳はNEOブロクチェーンを基づいています、合計50億個、10<sup>-8</sup>に精確できます，発行量は永遠に増加しません。',//
    total_content_item2: '第一回目の私募は5％です、2018年03月08日はホワイトリスト登録の締切日です。2018年02月15日までには早鳥期です。',
    total_content_item3: '2018年5月31日の前にGF通証は各投資家のNEOアドレスに転移します、二週間内に取引所に上場します。',

    community_video_title: 'コミュニティ運営',
    video_tag_tip: 'お使いブラウザがビデオタグをサポートしません',
    community_video_text1: '理解が難しいですか？大丈夫です、次の文字を見たら分かります',//
    community_video_text2: '簡単に言う、コミュニティ各役割の値の逆転行為はGFを流通書類としています。コインデーとコインデーの保証メカニズムで、ウーザーのGFの保有を励ます、クリックファーミング行為を避けます。コミュニティは異なる割合によって、ゲームクラウドファンディングとゲームリリースの成分を受け取ります。この成分の収入はコミュニティを構築と維持する以外、少なくとも50％はGFの所有割合によって対応するアドレスに定期的に配分されます。コミュニティの広めると成長につれて、もっと多くのウーザーがコミュニティに加入して、GFの切り上げは必然のことです。',//
    
}